### ISSUE TITLE
Text misaligned when `{org}/{repo}#{issue_number}` overflows available width

### ISSUE THREAD

**Issue by rithviknishad** [Ashesh3/github-activity#9]
<img width="1119" alt="image" src="https://github.com/Ashesh3/github-activity/assets/25143503/c56b4a5c-a730-42ee-94e7-80883f4912a1">

**Comment by Ashesh3** [comment]
![image](https://github.com/Ashesh3/github-activity/assets/3626859/1a7b8f34-5400-4d41-88fa-d8b96e66d86e)

Should be fixed! Also added URL query params for the state 😄
